mkaczanowski/packer-builder-arm

- boards/raspberry-pi/raspbian.json
I needed to make this change to boards/raspberry-pi/raspbian.json so packer could find /usr/sbin/chroot on Ubuntu 18.04.
> add /usr/sbin to chroot_env in raspian.json

- .github/workflows/all-boards.yml
- boards/jetson-nano/ubuntu.json
- boards/odroid-xu4/ubuntu.json
- boards/parallella/archlinuxarm.json
- boards/parallella/ubuntu.json
Also fix some minor findings in some board configurations:
* Add /usr/sbin to $PATH of image_chroot_env, otherwise chroot is not found (some boards
already had this set, other not).
* Remove trailing tick mark in parallela/archlinuxarm.json
jetson-nano/ubuntu.json is disabled as it does not build via the github
action, even though the board builds fine locally.
> Build all boards via github actions matrix build

- README.md
- builder/step_extract_and_copy_image.go
I added support for raw base images.
To skip the logic responsible for unpacking, specify `file_target_extension` as "img" or "iso" in `remote file config`.
> raw images support

- builder/step_create_base_image.go
- builder/step_mount_image.go
This allows creating huge empty images without consuming too much space on CI systems and it heavily speeds up writing the image to sd-cards if the sparse blocks are skipped.
The discard mount also makes blocks sparse again (loop-mounts support that since while), if during work on the mounted image files/blocks are deleted. An alternative could be calling `fstrim` right before doing umount.
> Make base image sparse and keep the sparseness by mounting with discard

- README.md
- boards/raspberry-pi/archlinuxarm.json
- scripts/bootstrap_resizerootfs.sh
- scripts/resizerootfs/resizerootfs
- scripts/resizerootfs/resizerootfs.service
Following up to the discussion and information in https://github.com/mkaczanowski/packer-builder-arm/issues/19
Adding as an example as this could be helpful for almost all boards and distributions.
Tested with rpi1b here.
Pinging @bcomnes who also participated in the related discussion.
> Add resizerootfs scripts and add to one board as example

- docker/Dockerfile
Without this, HTTPS connections (say, to download raspbian images) fail because they can't verify certificates.
ex.:
```
1 error(s) occurred:
* couldn't extract checksum from checksum file
```
> Dockerfile: add ca-certificates to final image

- README.md
This requires the activation of the Docker Cloud CI build vor `docker/Dockerfile` and the availability of the container named `mkaczanowski/packer-builder-arm`. After that the badges should refresh and show correct values.
> Add Docker Hub badges and details howto use the container from Docker Hub

- .dockerignore
Update .dockerignore as ignore ** + include some !directories causes issues.
This is fixed in newer Docker versions, but the Docker Hub Cloud Builder
seems to be still affected by this.
See also https://github.com/docker/compose/issues/6024
> Update .dockerignore to fix build with Docker Hub Cloud Builder

- .travis.yml
- README.md
- docker/entrypoint.sh
The docker container currently contains the bare minimum list of packages
to get an image built. By adding a parameter to the entrypoint.sh script
more packages can be installed along the way in a flexible way, without
the need to extend the provided container.
E.g. useable to add bmap-tools or zstd.
> Extend Docker entrypoint.sh to support installing extra-system-packages

- docker/entrypoint.sh
Otherwise shows error:
/entrypoint.sh: line 19: EXTRA_SYSTEM_PACKAGES[0]: unbound variable
Ping @rmb938 who reported this in https://github.com/mkaczanowski/packer-builder-arm/pull/31
> Fix Docker entrypoint when no -extra-system-packages are specified

- docker/Dockerfile
Without this the following error appears at the end of the packer build
```
==> arm: optional `fuser -k` failed with exec: "fuser": executable file not found in $PATH:
```
With the fix the following is printed at the end of the build
```
==> arm: optional `fuser -k` failed with exit status 1:
```
> install psmisc for fuser

- docker/Dockerfile
Hello! Great work with this plugin, very useful 🙏 
I have been using the Docker image since I'm on a Mac.  Today I tried resize mode and it fails because it tries to call `qemu-img` and `parted`, so I added them to the Dockerfile and it worked.
While I'm here, haven't looked at the go code yet, is there a way to not use a cached downloaded zip, and instead an already expanded local image file to start?  There is significant time spent unzipping and redundant installs, I'm looking to speed my workflow up here.  I tried `file://`, it mostly works (I think), but I also think it's wasting time with the checksum.
> Add qemu-utils + parted, needed for resize mode to work in Docker

- .github/workflows/all-boards.yml
- boards/raspberry-pi-3/raspios-lite-arm64.json
RaspberryPi Foundation is releasing 64bits version of their OS. 
The news is here: https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370
The lite 64bits image (probably more suitable for custom builds) is fetched from here: https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2020-08-24/
> Adds RaspberryPi OS 64bits (beta) lite version to the boards

- boards/raspberry-pi-3/archlinuxarm.json
According to [ArchlinuxARM documentation for the RaspberryPi 3](https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-3), one should either use RPi2 image or aarch64 image. 
In this case, I choose the aarch64 image since the qemu kernel is also using that architecture
> Fuxes build fail for RPi3 archlinuxarm image

- boards/raspberry-pi-4/ubuntu_server_20.04_arm64.json
This PR simply bumps the version of the base image and the checksum file URL to the latest release by Ubuntu. 
It seems that with the release of 20.04.**2**, the checksum file at the specified [URL](http://cdimage.ubuntu.com/releases/20.04.1/release/SHA256SUMS) no longer contains checksums for 20.04.**1**. This causes `packer build` command to fail with the following error message:
```
Error: Failed to prepare build: "arm"
1 error(s) occurred:
* couldn't extract checksum from checksum file
```
> Bump Ubuntu Server from 20.04.1 to 20.04.2 for PI-4

- builder/builder.hcl2spec.go
- builder/step_extract_and_copy_image.go
- config/remote_file_config.go
- config/remote_file_config.hcl2spec.go
It happened to me that the `/tmp` directory on my computer did not have enough available space when unpacking the initial image, so I added the option to chose another place to do it : `file_tmp_dir_location`. The behavior is the folowing:
- If it is unset or set to `""`, it defaults to `/tmp`;
- If it is set, then it will use the value as the base path.
> Feature : Adds ability to chose tmp directory location

- .travis.yml
- docker/Dockerfile
aarch64 containers also run pretty good on Apple M1 hardware.
Also get hadolint from ghrc.io (GitHub container registry) instead of Docker Hub to avoid pull rate limitations.
This is just the first step, the qemu stuff does not work on aarch64 and requires to be updated/deactivated in further commits.
> Support building the Docker Container for aarch64

- README.md
- builder/builder.go
- builder/step_chroot_provision.go
- docker/Dockerfile
- docker/entrypoint.sh
tonistiigi/binfmt is a drop in replacement for multiarch/qemu-user-static, which not only can emulate arm/arm64 on amd64 but also on arm64 and other architectures. By setting up qemu with Docker can automatically execute the binaries of other achitecture in the chroot without any additional setup.
This way the Docker Container can now be created for amd64 and aarch64. The aarch64 version also works on Linux aarch64 including Docker on Apple M1 hardware.
fixes https://github.com/mkaczanowski/packer-builder-arm/issues/76
Next step would be writing a Github action with buildx that builds and uploads a Docker multi-arch Docker image.
> Enable building on Linux/Mac arm64 with Docker

- .github/workflows/docker.yml
The ci/dockercloud builder does currently not support buildx multiarch building... There are several open tickets and people tried all kind of tricks via hooks, but none of those work.
Via Github actions this is all easily possible and enables building and uploading multi-arch images.
This requires deactivating the ci/dockercloud builder and adding a Docker Hub user + created token to the repo secrets via an environment (named `docker`) restricted to the master branch.
(The commented lines also show how to additional upload to the Github container registry ghcr.io, which has no pull rate-limitation, but requires another upload token to be added via secrets).
> Build + Upload multi-arch docker image via Github actions

- .github/workflows/docker.yml
Also:
* remove not required if master login conditional.
* remove environment name specification, as secrets seem to be accessible without (seen that in the other workflows). Is that correct?
Without `push: true` the following message is show during the action run:
time="2021-04-20T18:59:19Z" level=warning msg="No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load"
Also looking at the green tick on master branch: it seems that the Docker Hub Builder is still triggered and building.
> Set push: true to really push the docker image

- .github/workflows/archlinuxarm-armv7-docker.yml
- .github/workflows/archlinuxarm-armv8-docker.yml
Both workflows are normally not triggered, if PRs come from forks. If a PR comes from an internal branch (no fork, like from the Github dependapot service, see other open PR https://github.com/mkaczanowski/packer-builder-arm/pull/84) those two pipelines fail, as they do not have access to secrets. Pushing from a non-master branch anyway seems to be not desirable.
> Restrict armv{7,8} docker workflows to master branch

- .github/dependabot.yml
See also https://docs.github.com/en/code-security/supply-chain-security/keeping-your-actions-up-to-date-with-dependabot
> Extend dependabot to update Github actions

- docker/hooks/push
Checking the status tick on latest commit on master tells, that the Docker ci/dockercloud-stage builder is still building and pushing the linux/amd64 image and thus overwriting the multiarch linux/arm64 + linux/amd64 image+manifest pushed by the Github buildx action, which often pushes a bit earlier and thus gets overwritten: https://hub.docker.com/r/mkaczanowski/packer-builder-arm/tags?page=1&ordering=last_updated
Using a hook in the repo pushing by the Docker ci/dockercloud-stage builder can be avoided, by overwriting the the default push command to do nothing: https://docs.docker.com/docker-hub/builds/advanced/
> Add docker push hook to stop Docker ci/dockercloud-stage from pushing

- docker/Dockerfile
ECR is not rate limited compared to Dockerhub and thus makes CI more reliable.
closes https://github.com/mkaczanowski/packer-builder-arm/issues/107
> Switch to Docker base images from public AWS ECR registry

- .travis.yml
The Dockerhub version causes rate-limited related failures.
Also switching to Ubuntu focal (20.04) on travis (instead of the default Ubuntu Xenial 16.04) to have newer shellcheck >=0.7.0 available.
> Run pre-installed shellcheck on travis instead of the Dockerhub version

- docker/entrypoint.sh
The Docker container can be used on linux-{amd64, aarch64} and macOS intel/apple silicon (M1). Printing the uname output helps to understand what underlying architecture is used.
Also not hiding the binfmt install out helps to understand what is wrong in cases where that command fails.
> Increase docker entrypoint verbosity for better debugging

- docker/Dockerfile
It appears that the bitnami golang image is only distributed for the `linux/amd64` platform. This means that while `packer-builder-arm` builds for `linux/arm64` will succeed, the packer binary throws an error:
```
$ docker run --rm --privileged --platform linux/arm64 -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build boards/raspberry-pi/raspbian.json
uname -a:  Linux 71aaac6d94db 5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
{
"supported": [
"linux/arm64",
"linux/amd64",
"linux/riscv64",
"linux/ppc64le",
"linux/s390x",
"linux/386",
"linux/mips64le",
"linux/mips64",
"linux/arm/v7",
"linux/arm/v6"
],
"emulators": [
"qemu-arm",
"qemu-i386",
"qemu-mips64",
"qemu-mips64el",
"qemu-ppc64le",
"qemu-riscv64",
"qemu-s390x", …
```
> Fix qemu error on ARM64 builds

- .github/workflows/all-boards.yml
- boards/raspberry-pi/raspios-lite-arm.json
Added configuration file for most recent raspios lite edition supported by all Raspberry Pi models
> feat: add raspios lite 32 bit board

- .github/workflows/docker.yml
Containers built from master branch on merge/cron builds will be tagged *master*, *latest* will point to the latest version taggeded container.
Also update the docker description on merge as it got out of sync.
> Add Docker meta for git release/tag based container tagging

- .github/workflows/test.yml
- Vagrantfile
- builder/step_setup_qemu.go
Supports newer qemu-user-static versions (like in Ubuntu 22.04) where `/usr/libexec/qemu-binfmt/aarch64-binfmt-P` is registered under `/proc/sys/fs/binfmt_misc` as interpreter that is a relativ symlink, which points to `../../bin/qemu-aarch64-static`. Testing this via vagrant.
> Add vagrant test workflow, enable handling qemu binaries being symlinks

- .github/workflows/test.yml
- README.md
- docker/Dockerfile
- docker/entrypoint.sh
* Run vagrant test on macos-12: macos-10.15 runners are deprecated now and the macos-11 runners don't
support vagrant.
* Enable extended packer logging to see plugin loading details
* Extend Docker section in README.md regarding mac usage
* Quit docker processing if packer-* binary is found in current folder: To avoid `error initializing builder 'arm': fork/exec /build/packer-builder-arm: exec format error` as mentioned in the README.md.
* Build from local source only in Docker
closes https://github.com/mkaczanowski/packer-builder-arm/issues/130
> Improve Mac (Intel/M1) container experience

- .github/workflows/archlinuxarm-armv7-docker.yml
- .github/workflows/archlinuxarm-armv8-docker.yml
- boards/armv7/archlinuxarm-docker.json
- boards/armv8/archlinuxarm-docker.json
Also:
* install packer via action
* Remove "Setup Backports" step as not neaded by newer Action Runners and trusty being old (ubuntu-latest runners use 20.04, trusty is 14.04)
> Set Docker platforms for archlinuxarm containers

- docker/Dockerfile
Requires to explicitly add fdisk as dependency (provides sfdisk).
Also sorting the apt-get installed dependencies.
> Update Docker container to Ubuntu Jammy (=22.04 LTS)

- .dockerignore
- .github/workflows/docker.yml
- docker/Dockerfile
- docker/entrypoint.sh
packer-builder-arm is using qemu in order to emulate the arm target platform when provisioning arm machine images.
The Docker Container therefor contains embedded qemu binaries and some setup code to register those when using the container. This integration didn't work and that was not caught by the Github workflows due the `docker/setup-qemu-action` always being running as part of the docker workflow. The usage of `docker/setup-qemu-action` enables two things: 1. building multi-arch containers 2. running binaries of other platforms inside a container. The later should be covered by the qemu binaries+setup we integrated into the container. By setting up `docker/setup-qemu-action` only when we build+push multi-arch containers on the master-brach/release, we get the qemu integration tested …
> Fix qemu container integration
