mkaczanowski/packer-builder-arm

.editorconfig, .github/workflows/archlinuxarm-armv7-docker.yml, .github/workflows/archlinuxarm-odroid-xu4.yml, .travis.yml, boards/armv7/archlinuxarm-docker.json, boards/bananapi-r1/archlinuxarm.json, boards/beaglebone-black/archlinuxarm.json, boards/beaglebone-black/debian.json, boards/jetson-nano/ubuntu.json, boards/odroid-u3/archlinuxarm.json, boards/odroid-xu4/archlinuxarm.json, boards/odroid-xu4/ubuntu.json, boards/parallella/archlinuxarm.json, boards/parallella/ubuntu.json, boards/raspberry-pi/archlinuxarm.json, boards/raspberry-pi/raspbian.json, boards/wandboard/archlinuxarm.json
Let me know if your not interested in style changes just yet and I'll rebase them out to another branch.
=> beaglebone: Fix chroot not found - add /usr/sbin to PATH

builder/builder.go, builder/step_mount_image.go, config/image_config.go
=> add image mount path config option

config/image_config.go
As per title, not much to add...
=> New additional_chroot_mounts config

.dockerignore, .travis.yml, docker/Dockerfile, docker/entrypoint.sh
For details see the individual commit messages :)
Testing using travis-ci to distribute the CI jobs between the different CI providers.
Would be nice to see the Docker container uploaded to Docker Hub (Login in there via Github user and registering the repo should be enough). The README.md could be then updated regarding the usage.
Pinging also @belkone who provided the initial Dockerfile.
Thanks
=> Enhance, shrink and test Docker container

README.md, docker/Dockerfile, docker/entrypoint.sh
continuation of the thread https://github.com/mkaczanowski/packer-builder-arm/pull/22 with @dbast ;) 
Inspired by https://github.com/mkaczanowski/packer-builder-arm/issues/17
=> simplified dockerfile

.github/workflows/all-boards.yml, README.md, boards/raspberry-pi-3/archlinuxarm.json, boards/raspberry-pi-4/archlinuxarm.json
This builds on https://github.com/mkaczanowski/packer-builder-arm/pull/24 but also incorporates the discussion in https://github.com/mkaczanowski/packer-builder-arm/issues/15 regarding Armv8 quemu binaries.
=> Add armv8 Raspi 4 example

README.md, boards/raspberry-pi-4/ubuntu_server_20.04_arm64.json
=> add ubuntu server 20.04 LTE board definition for rpi4

boards/raspberry-pi-4/ubuntu_server_20.04_arm64.json
=> fix mount point for ubuntu 20.04 on raspi4

.github/workflows/all-boards.yml
=> Update Go to 1.15

README.md
Related to issue #21, which is how I came here.  The Readme is great, but was missing the detail added.
=> [Doc] Clarify resize instructions

boards/beaglebone-black/ubuntu.hcl
Add a commented example showing:
- Build comments
- Image resizing (Issue #21)
- Network access (Issue #16)
=> [Doc] Ubuntu resize example.

README.md
=> [Doc] Update resize example links

.github/workflows/all-boards.yml
=> [CICD] Add Ubuntu resize HCL example

docker/Dockerfile
use upx with --lzma to solve https://github.com/mkaczanowski/packer-builder-arm/issues/103
=> [RFC] use upx with --lzma to solve #103

builder/step_extract_and_copy_image.go, builder/step_populate_filesystem.go
Minor one, but this shows up in the output.
Thanks!
=> Fix a typo in the word "command"

builder/step_map_image.go
It may happen that between checking for free loopback device
and setting it up, another process will take that device.
There is a high chance for collision when multiple parallel builds
are being done from the same image file as seen in #163.
Instead of manually trying to find and acquire device, lets
use the losetup for that. When looking for free device, according
to ![manual][1] we can also specify a image to attach.
To know the device which is mapped to image, additional flag
is set, so that losetup will print the mapped device.
Short flags are replaced with longer version for easier
understanding of their meaning.
[1]: https://man.archlinux.org/man/losetup.8.en
=> Use losetup find and attach to avoid race condition

README.md
Also add container version badge.
=> Show Github workflow instead of outdated travis badge

.github/workflows/test.yml, boards/beaglebone-black/ubuntu.pkr.hcl, boards/raspberry-pi-4/ubuntu_server_20.04_arm64.pkr.hcl
No real code changes, but some preparations / examples in the lights of plugins https://github.com/mkaczanowski/packer-builder-arm/pull/172
=> Call packer init for .hcl files to install specified plugins

README.md, boards/raspberry-pi/raspbian.json
closes https://github.com/mkaczanowski/packer-builder-arm/issues/159
=> Add armv6l instructions to readme

.pre-commit-config.yaml, README.md, builder/step_expand_partition.go, builder/step_setup_qemu.go
closes https://github.com/mkaczanowski/packer-builder-arm/issues/210
Also some minor spell fixes.
=> Add download protocol hints to readme

README.md
Due to https://github.com/badges/shields/issues/8671
=> Fix Build Status badge

docker/Dockerfile, docker/entrypoint.sh
Instead add qemu-x86_64-static.
=> Remove qemu-aarch64-static from linux-aarch64 container

.github/workflows/test.yml, boards/rock-4b/debos-radxa.pkr.hcl
closes https://github.com/mkaczanowski/packer-builder-arm/issues/251
=> Add rock-4b debos-radxa Debian 11 example
